### ISSUE TITLE
Database schema missing ?

### ISSUE THREAD

**Issue by omars44** [navs-svan/Beatport-DJCharts-Scraper#1]
```
637278e2b206# pdm run start artist -a blawan
Traceback (most recent call last):
  File "/app/main.py", line 358, in <module>
    by_artist(
  File "/app/main.py", line 93, in by_artist
    cur.execute(query, (artist,))
  File "/app/.venv/lib/python3.12/site-packages/psycopg2/extras.py", line 236, in execute
    return super().execute(query, vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "tracks" does not exist
LINE 6:                     FROM tracks
```

**Comment by navs-svan** [comment]
You need to scrape the DJ charts first using [pipeline.py](https://github.com/navs-svan/Beatport-Spotify/blob/main/pipeline.py). Table creation is automatic but the schema is located here in [lines 45-62](https://github.com/navs-svan/Beatport-Spotify/blob/main/beatportscraper/pipelines.py) if you want to edit it on your own. 

Alternatively, using the schema mentioned above, manually execute it then import the following [csv file](https://drive.google.com/file/d/1xgKlh7uKEAyh7C0BK_FwTy2M_Ti_cgLr/view?usp=sharing). The link leads to a google drive containing the tracks table as of April 7, 2024 (not recommended since this would mess with the scrapy-deltafetch cache)
